### ISSUE TITLE
KeywordImport Service Structure

### ISSUE THREAD

**Issue by olivierobert** [rajibds/google-search-from-csv#30]
Of all the services, this service the gem `interactor-rails`, thus is structured slightly differently. So I have a few questions:

1. Why is it necessary to rescue from `ActiveRecord::RecordNotFound`? In which cases does that happen?
2. Did you consider using ActiveModel instead of rolling out a custom implementation to track errors? This is similar to using Form Objects (here is [an article from Nimble's blog](https://nimblehq.co/blog/lets-play-design-patterns-form-objects)). Which disadvantages would you see in using it?

**Comment by rajibds** [comment]
1.  it's not necessary actually, removed in https://github.com/rajibds/google-search-from-csv/pull/38/commits/5bcacd54dc4f5775c66a2af1130063714a1df716, Thanks for pointing it out
2. Thanks for the article
Regarding using form objects, I thought of something like:

```ruby
class KeywordsForm
  include ActiveModel::Model
  
  # then could use the errors object to add errors
  # to remain consistent with the current implementation, something like:
  
  errors.add(:base, {
    row: row_number,
    message: keyword.errors.full_messages.to_sentence,
    }
  )
```

As the `file` validation happening in the `ImportCsv` class, I thought the other validations were model-specific, so  I thought of being explicit about the `success` and `errors` objects. I'd definitely go for the form object pattern if the validations were specific to the implementation class(i.e `KeywordsForm` in this case). @olivierobert

**Comment by olivierobert** [comment]
The fix you made to remove the unnecessary rescue is fine 👍 

As for your understanding of the form objects, that is correct. In terms of validations, the form object pattern is great to house all validations, even across multiple models, so the validation for the file presence and well-formed keywords could be together. Again, nothing fundamentally wrong with the current implementation though :-)

**Comment by rajibds** [comment]
@olivierobert , Thanks for the insight regarding housing validations across multiple models, will keep that in mind, certainly a great weapon added to my arsenal!
