### ISSUE TITLE
Local Setup Failure

### ISSUE THREAD

**Issue by olivierobert** [rajibds/google-search-from-csv#32]
I followed the README fails that has the following instructions:

```
docker-compose up --build
docker-compose run web rails db:setup
```

But the first command fails with the following error:

![image](https://user-images.githubusercontent.com/696529/149145522-4868cc5b-a1ae-4a83-ab4a-b6104af792fc.png)

**Comment by rajibds** [comment]
interesting, I reran the containers from scratch and it ran successfully
![image](https://user-images.githubusercontent.com/39977805/149198641-9c239587-6571-4f34-8216-12c6bac98ca3.png)

**Comment by olivierobert** [comment]
Cleared the previous images and rebuilt them from scratch. Worked like a charm today 🍀 

![image](https://user-images.githubusercontent.com/696529/149284582-c52fc36d-701a-4c31-9927-abb49e44de33.png)
