### ISSUE TITLE
Extract React JS Component into Pages/Screens

### ISSUE THREAD

**Issue by olivierobert** [rajibds/google-search-from-csv#33]
Since the whole UI is rendered via React JS, the current structure of components could be improved by having another organization level that can be called pages or screens. This would allow separating UI components (that are parts of the UI) from pages/screens components (that represents whole pages).

![image](https://user-images.githubusercontent.com/696529/149146208-f18ed1b5-088b-458b-b8ab-3035a506ee4c.png)

The organization of files would be clearer (especially for newcomers to the codebase like me 😉) and easier to maintain over time.

This structure is quite standard in the JS community and even adopted by popular frameworks like Next.JS (see [docs](https://nextjs.org/docs/basic-features/pages)).

**Comment by rajibds** [comment]
@olivierobert, I really liked the idea of moving route/ui specific components to `pages` folder, done in https://github.com/rajibds/google-search-from-csv/pull/36, Thank you!
