### ISSUE TITLE
Non-standard folder naming

### ISSUE THREAD

**Issue by caherrerapa** [rajibds/google-search-from-csv#34]
Rails works heavily using conventions. It's important to follow them to make sure the constants are created properly and work on any platform (win, *unix). In this case the module folder structure is not following the conventions.

<img width="632" alt="google-search-from-csv_app_services_at_main_·_rajibds_google-search-from-csv" src="https://user-images.githubusercontent.com/1084920/149150916-0347f8a3-eeb9-4f64-8d56-7674ee113cc6.png">

**Comment by rajibds** [comment]
@caherrerapa , Thanks for pointing it out, fixed in https://github.com/rajibds/google-search-from-csv/pull/35
